CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_GPIO_HOGS=y
CONFIG_GPIO_HOGS_INIT_PRIORITY=80
CONFIG_GPIO_PCA_SERIES=y
CONFIG_GPIO_PCA_SERIES_INTERRUPT=y
CONFIG_HEAP_MEM_POOL_SIZE=8192
CONFIG_NEWLIB_LIBC=y
CONFIG_NVS=y
CONFIG_PICOLIBC=n
CONFIG_SETTINGS_NVS=y
